# Generated by Django 2.0 on 2018-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180827_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
