# Generated by Django 2.0.7 on 2018-07-23 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applyed_usera',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
