# Generated by Django 2.0.7 on 2018-07-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobs_applyed_usera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='applyed_usera',
            new_name='applyed_users',
        ),
    ]
