# Generated by Django 2.0.7 on 2018-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180723_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
