# Generated by Django 2.0 on 2018-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180820_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
    ]
