# Generated by Django 2.0.7 on 2018-07-23 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_jobs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='saved_users',
            field=models.ManyToManyField(related_name='saved_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
