# Generated by Django 2.0.7 on 2018-07-25 18:52

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobs_saved_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=0, upload_to=app.validators.image_path),
        ),
    ]
