# Generated by Django 2.0.7 on 2018-07-25 19:33

import app.validators
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180725_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to=app.validators.image_path),
        ),
    ]
