# Generated by Django 2.0.7 on 2018-07-25 19:36

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180725_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=0, upload_to=app.validators.image_path),
        ),
    ]
