# Generated by Django 2.0.7 on 2018-07-25 20:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180725_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
