# Generated by Django 2.0 on 2018-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180804_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='tags',
            field=models.TextField(default='', max_length=100),
        ),
    ]
