# Generated by Django 2.0 on 2018-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
